sources:
  - surveys-assignment/Sources
templates:
  - tools/sourcery/templates
output:
  surveys-assignmentTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - surveys-assignment
  autoMockableImports:
    - RxSwift
    - RxCocoa
